<div id="footer_container">
    <p><b>Author</b>: Anthony Lavertu (2024)</p>
    <p><b>Generated by</b> <a href="https://pdoc3.github.io/pdoc" title="pdoc: Python API documentation generator"><cite>pdoc</cite> ${pdoc.__version__}</a>.</p>
</div>