<!doctype html>
<html lang="${html_lang}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />
  <link rel="icon" type="image/x-icon" href="${absolute_path}/assets/favicon.ico">
  <link href='${absolute_path}/assets/bootstrap.min.css' rel='stylesheet', type='text/css'>
  <link href="${absolute_path}/assets/navbar.css" rel="stylesheet" type="text/css">
  <link href="${absolute_path}/assets/basic.css" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" crossorigin="anonymous" />
  <script src="${absolute_path}/assets/bootstrap.min.js"></script>
  <title>${page_title}</title>
  <meta name="description" content="${page_desc}" />
</head>
<body>
  <%include file="head.mako"/>
  <div class="container">
    ${page_content}
  </div>
  <div class="divider"></div>
  <footer id="footer">
    <%include file="footer.mako"/>
    <p>Generated by <a href="https://pdoc3.github.io/pdoc" title="pdoc: Python API documentation generator"><cite>pdoc</cite> ${pdoc.__version__}</a>.</p>
</footer>
</body>
  <script>
      document.querySelectorAll('.copy-button').forEach(button => {
      button.addEventListener('click', () => {
        const codeElement = button.parentElement.querySelector('pre');
        const codeText = codeElement.textContent;

        navigator.clipboard.writeText(codeText).then(() => {
          console.log('Code copied to clipboard');
        }).catch(err => {
          console.error('Failed to copy code: ', err);
        });
      });
    });
  </script>
</html>